### ISSUE TITLE
Kan ikke starte tur på ios, appen krasjer

### ISSUE THREAD

**Issue by Bjornar97** [Bjornar97/Bachelor-Interaktivt-Kart#29]
- Når man prøver å starte en tur på ios, krasjer appen.

**Comment by mnkvm** [comment]
[error_log_tracking_ios.txt](https://github.com/Bjornar97/Bachelor-Interaktivt-Kart/files/2888662/error_log_tracking_ios.txt)

**Comment by mnkvm** [comment]
[error_log_tracking_ios_2.txt](https://github.com/Bjornar97/Bachelor-Interaktivt-Kart/files/2904808/error_log_tracking_ios_2.txt)

**Comment by Bjornar97** [comment]
På grunn av at vi ikke har lagt inn background-mode på ios, så kan vi ikke ha iosAllowsBackgroundLocationUpdates til true. 

Linje: 132 og 178 i tracker.ts
